openapi: 3.0.0  # version of api
info:
  title: product Cataloug API
  description: this API will contain lot of product information
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: local server
paths:
  /products/createProduct:
    post:
      summary: create a new product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
            description: product created successfully
        '201':
            description: created
        '400':
            description: bad request
        '404':
            description: not found
        '500':
            description: internal server error
components:
  schemas:
    Product:
      type: object
      required:
        - productNumber
        - productName
        - productValue
      properties:
        productNumber:
          type: Integer
        productName:
            type: string
        productValue:
          type: number
