openapi: 3.0.0  # version of api
info:
  title: product Cataloug API
  description: this API will contain lot of product information
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: local server
paths:
  /products/createProduct:
    post:
      summary: create a new product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      parameters:
        - name: x-td-request-id
          in: header
          description: request id for tracking
          required: true
          schema:
            type: string
        - name: x-td-email
          in: header
          description: email of the user
          required: true
          schema:
            type: string
          x-parameter-extra-annotation: |
            @com.td.productCatalog.annotations.ValidEmailHeader
        - name: x-td-uid
          in: header
          description: user id
          required: false
          schema:
            type: string
        - name: x-td-app-name
          in: header
          description: application name
          required: false
          schema:
            type: string
      responses:
        '200':
            description: product created successfully
        '201':
            description: created
        '400':
            description: bad request
        '404':
            description: not found
        '500':
            description: internal server error
components:
  schemas:
    Product:
      type: object
      required:
        - productNumber
        - productName
        - productValue
      properties:
        productNumber:
          type: integer
        productName:
            type: string
        productValue:
          type: number
